version: "3.2"
# docker-compose build
# docker-compose up -d
# docker-compose up -d --force-recreate --build
# docker-compose up -d --force-recreate
# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic FileRead


# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic FileRead

# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-topics.sh --list --zookeeper zookeeper:2181

# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic FileRead --from-beginning


 
# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list kafka:9092 --topic FileRead --time -1
 
# docker exec -it zookeeper zookeeper-shell.sh localhost:2181 <<< "ls /brokers/ids"
 
 # /opt/zookeeper-3.4.9/bin/zkCli.sh -server 127.0.0.1:2181
networks:
  msing:

services:

  filereader:
    build: 
      context: .\
      dockerfile: FileReaderDockerfile
    environment:      
      - ContainerFlag=1 
      - InputLocation=/volume 
      - NotificationTarget=http://signalr:80 
      - KafkaServerAddress=kafka:9092
      - FileReadTopicName=FileRead         
    container_name: my-filereader    
    networks:
      - msing 
    links:
      - kafka
    volumes:
      - "C:/input:/volume"
    depends_on:
      - signalr

  signalr:
    build: 
      context: .\
      dockerfile: SignalRHubDockerfile    
    container_name: signalrhub
    ports:
      - "5555:80"
    environment:
      - KafkaServerAddress=kafka:9092
      - FileReadTopicName=FileRead      
    networks:
      - msing 
    depends_on:
      - kafka
    links:
      - kafka:kafka
    
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - msing 
    ports:
      - "2181:2181"
  kafka:  
    container_name: kafka
    image: wurstmeister/kafka
    networks:
      - msing 
    ports:
      - "9092:9092"
    environment:
      #- KAFKA_CREATE_TOPICS=FileRead:1:1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.12:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181    
    volumes:
      - C:/somekafkashit:/var/run/docker.sock
