version: "3.2"
# docker-compose build
# docker-compose up -d
# docker-compose up -d --force-recreate --build
# docker-compose up -d --force-recreate
# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic FileRead

# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic FileContent

# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic FileRead

# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-topics.sh --list --zookeeper zookeeper:2181

# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic FileRead --from-beginning


 
# docker exec -it kafka /opt/kafka_2.11-2.0.0/bin/kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list kafka:9092 --topic FileRead --time -1
 
# docker exec -it zookeeper zookeeper-shell.sh localhost:2181 <<< "ls /brokers/ids"
 
 # /opt/zookeeper-3.4.9/bin/zkCli.sh -server 127.0.0.1:2181
 
# docker-compose up -d --force-recreate --build signalr
# docker-compose up -d --build filereader
# OpenCover.Console.exe -oldstyle -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" -targetargs:"C:\Projects\MicroservicingAround\MsingBackend\FileReaderTest\bin\Debug\netcoreapp2.1\FileReaderTest.dll" -filter:"+[*]* -[*Test]*" -output:opencovertests.xml -mergebyhash
# "C:\Projects\ReportGenerator\net47\ReportGenerator.exe" -reports:C:\Projects\MicroservicingAround\MsingBackend\FileReaderTest\bin\Debug\netcoreapp2.1\opencovertests.xml -targetdir:coverage

networks:
  msing:

services:

  filereader:
    build: 
      context: .\
      dockerfile: FileReaderDockerfile
    environment:      
      - InputLocation=/volume/input
      - ProcessedLocation=/volume/processed      
      - NotificationTarget=http://signalr:80 
      - KafkaServerAddress=kafka:9092
      - FileReadTopicName=FileRead   
      - FileContentTopicName=FileContent
    container_name: my-filereader    
    networks:
      - msing 
    links:
      - kafka
    volumes:
      - "C:/input:/volume"

  incomingmessagehandler:
    build: 
      context: .\
      dockerfile: IncomingMessageHandlerDockerFile
    environment:      
      - ServerAddress=kafka:9092
      - FileContentChannel=FileContent         
    container_name: imh    
    networks:
      - msing 
    depends_on:
      - kafka
      
  signalr:
    build: 
      context: .\
      dockerfile: SignalRHubDockerfile    
    container_name: signalrhub
    ports:
      - "5555:80"
    environment:      
      - ServerAddress=kafka:9092
      - FileReadChannel=FileRead      
    networks:
      - msing 
    depends_on:
      - kafka
    links:
      - kafka:kafka
    
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - msing 
    ports:
      - "2181:2181"
  kafka:  
    container_name: kafka
    image: wurstmeister/kafka
    networks:
      - msing 
    ports:
      - "9092:9092"
    environment:
      #- KAFKA_CREATE_TOPICS=FileRead:1:1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.12:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181    
    volumes:
      - C:/somekafkashit:/var/run/docker.sock
